name: "Main CI/CD"

on:
  push:
    branches:
      - "main"

jobs:
  checks:
    name: "Checks"
    runs-on: "ubuntu-latest"
    steps:
      - name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node with Yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Build code
        run: yarn build

      - name: Run checks
        run: yarn checks

  deploy-prod:
    name: Deploy to Production
    environment: Api__prod
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - name: Cancel previous workflows
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        uses: superfly/flyctl-actions@1.3
        with:
          args: |
            deploy --dockerfile ./Dockerfile \
              --strategy immediate --now --app api--prod --detach --remote-only \
              --build-arg APP=backend \
              -e FRONT_BASE_URL=https://h.veetik.com \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e G_CLIENT_ID=${{ secrets.G_CLIENT_ID }} \
              -e G_CLIENT_SECRET=${{ secrets.G_CLIENT_SECRET }} \
              -e G_CLIENT_REDIRECT_URI=https://h-api.veetik.com/google-auth/callback \
              -e JWT_AUDIENCE=h.veetik.com \
              -e JWT_ISSUER=h-api.veetik.com \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e PORT=5000
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
